const Tout = [
  {
    'code': 'DZ',
    'pays': 'Algérie',
    'reponses': ['Alger', 'Oran', 'Constantine', 'Annaba'],
    'capitale': 'Alger',
  },
  {
    'code': 'AO',
    'pays': 'Angola',
    'reponses': ['Luanda', 'Lubango', 'Cabinda', 'Benguela'],
    'capitale': 'Luanda',
  },
  {
    'code': 'BJ',
    'pays': 'Bénin',
    'reponses': ['Porto-Novo', 'Cotonou', 'Parakou', 'Abomey'],
    'capitale': 'Porto-Novo',
  },
  {
    'code': 'BW',
    'pays': 'Botswana',
    'reponses': ['Gaborone', 'Francistown', 'Maun', 'Serowe'],
    'capitale': 'Gaborone',
  },
  {
    'code': 'BF',
    'pays': 'Burkina Faso',
    'reponses': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora'],
    'capitale': 'Ouagadougou',
  },
  {
    'code': 'BI',
    'pays': 'Burundi',
    'reponses': ['Bujumbura', 'Gitega', 'Ngozi', 'Ruyigi'],
    'capitale': 'Bujumbura',
  },
  {
    'code': 'CV',
    'pays': 'Cabo Verde',
    'reponses': ['Praia', 'Mindelo', 'Santa Maria', 'Assomada'],
    'capitale': 'Praia',
  },
  {
    'code': 'CM',
    'pays': 'Cameroun',
    'reponses': ['Yaoundé', 'Douala', 'Bamenda', 'Bafoussam'],
    'capitale': 'Yaoundé',
  },
  {
    'code': 'CF',
    'pays': 'République centrafricaine',
    'reponses': ['Bangui', 'Bimbo', 'Berbérati', 'Carnot'],
    'capitale': 'Bangui',
  },
  {
    'code': 'TD',
    'pays': 'Tchad',
    'reponses': ['N\'Djamena', 'Moundou', 'Sarh', 'Abeche'],
    'capitale': 'N\'Djamena',
  },
  {
    'code': 'KM',
    'pays': 'Comores',
    'reponses': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni'],
    'capitale': 'Moroni',
  },
  {
    'code': 'CD',
    'pays': 'République démocratique du Congo',
    'reponses': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga'],
    'capitale': 'Kinshasa',
  },
  {
    'code': 'DJ',
    'pays': 'Djibouti',
    'reponses': ['Djibouti', 'Ali Sabieh', 'Tadjoura', 'Obock'],
    'capitale': 'Djibouti',
  },
  {
    'code': 'EG',
    'pays': 'Égypte',
    'reponses': ['Le Caire', 'Alexandrie', 'Gizeh', 'Port-Saïd'],
    'capitale': 'Le Caire',
  },
  {
    'code': 'GQ',
    'pays': 'Guinée équatoriale',
    'reponses': ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe'],
    'capitale': 'Malabo',
  },
  {
    'code': 'ER',
    'pays': 'Érythrée',
    'reponses': ['Asmara', 'Keren', 'Massawa', 'Assab'],
    'capitale': 'Asmara',
  },
  {
    'code': 'ET',
    'pays': 'Éthiopie',
    'reponses': ['Addis-Abeba', 'Dire Dawa', 'Nakfa', 'Bahir Dar'],
    'capitale': 'Addis-Abeba',
  },
  {
    'code': 'GA',
    'pays': 'Gabon',
    'reponses': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem'],
    'capitale': 'Libreville',
  },
  {
    'code': 'GM',
    'pays': 'Gambie',
    'reponses': ['Banjul', 'Serekunda', 'Brikama', 'Bakau'],
    'capitale': 'Banjul',
  },
  {
    'code': 'GH',
    'pays': 'Ghana',
    'reponses': ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi'],
    'capitale': 'Accra',
  },
  {
    'code': 'GN',
    'pays': 'Guinée',
    'reponses': ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia'],
    'capitale': 'Conakry',
  },
  {
    'code': 'GW',
    'pays': 'Guinée-Bissau',
    'reponses': ['Bissau', 'Bolama', 'Gabú', 'Bafatá'],
    'capitale': 'Bissau',
  },
  {
    'code': 'CI',
    'pays': 'Côte d\'Ivoire',
    'reponses': ['Yamoussoukro', 'Abidjan', 'Bouaké', 'Daloa'],
    'capitale': 'Yamoussoukro',
  },
  {
    'code': 'KE',
    'pays': 'Kenya',
    'reponses': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
    'capitale': 'Nairobi',
  },
  {
    'code': 'LS',
    'pays': 'Lesotho',
    'reponses': ['Maseru', 'Teyateyaneng', 'Leribe', 'Mafeteng'],
    'capitale': 'Maseru',
  },
  {
    'code': 'LR',
    'pays': 'Libéria',
    'reponses': ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville'],
    'capitale': 'Monrovia',
  },
  {
    'code': 'LY',
    'pays': 'Libye',
    'reponses': ['Tripoli', 'Benghazi', 'Misrata', 'Sirte'],
    'capitale': 'Tripoli',
  },
  {
    'code': 'MG',
    'pays': 'Madagascar',
    'reponses': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa'],
    'capitale': 'Antananarivo',
  },
  {
    'code': 'MW',
    'pays': 'Malawi',
    'reponses': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
    'capitale': 'Lilongwe',
  },
  {
    'code': 'ML',
    'pays': 'Mali',
    'reponses': ['Bamako', 'Sikasso', 'Ségou', 'Mopti'],
    'capitale': 'Bamako',
  },
  {
    'code': 'MR',
    'pays': 'Mauritanie',
    'reponses': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Zouérat'],
    'capitale': 'Nouakchott',
  },
  {
    'code': 'MU',
    'pays': 'Maurice',
    'reponses': [
      'Port-Louis',
      'Beau Bassin-Rose Hill',
      'Vacoas-Phoenix',
      'Curepipe'
    ],
    'capitale': 'Port-Louis',
  },
  {
    'code': 'MA',
    'pays': 'Maroc',
    'reponses': ['Rabat', 'Casablanca', 'Fès', 'Marrakech'],
    'capitale': 'Rabat',
  },
  {
    'code': 'MZ',
    'pays': 'Mozambique',
    'reponses': ['Maputo', 'Matola', 'Beira', 'Nampula'],
    'capitale': 'Maputo',
  },
  {
    'code': 'NA',
    'pays': 'Namibie',
    'reponses': ['Windhoek', 'Rundu', 'Walvis Bay', 'Oshakati'],
    'capitale': 'Windhoek',
  },
  {
    'code': 'NE',
    'pays': 'Niger',
    'reponses': ['Niamey', 'Zinder', 'Maradi', 'Agadez'],
    'capitale': 'Niamey',
  },
  {
    'code': 'NG',
    'pays': 'Nigeria',
    'reponses': ['Abuja', 'Lagos', 'Kano', 'Ibadan'],
    'capitale': 'Abuja',
  },
  {
    'code': 'RW',
    'pays': 'Rwanda',
    'reponses': ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'],
    'capitale': 'Kigali',
  },
  {
    'code': 'ST',
    'pays': 'Sao Tomé-et-Principe',
    'reponses': ['São Tomé', 'Neves', 'Trindade', 'Santana'],
    'capitale': 'São Tomé',
  },
  {
    'code': 'SN',
    'pays': 'Sénégal',
    'reponses': ['Dakar', 'Thiès', 'Kaolack', 'Ziguinchor'],
    'capitale': 'Dakar',
  },
  {
    'code': 'SC',
    'pays': 'Seychelles',
    'reponses': ['Victoria', 'Anse Boileau', 'Beau Vallon', 'Cascade'],
    'capitale': 'Victoria',
  },
  {
    'code': 'SL',
    'pays': 'Sierra Leone',
    'reponses': ['Freetown', 'Bo', 'Kenema', 'Makeni'],
    'capitale': 'Freetown',
  },
  {
    'code': 'SO',
    'pays': 'Somalie',
    'reponses': ['Mogadiscio', 'Hargeisa', 'Bosaso', 'Kismayo'],
    'capitale': 'Mogadiscio',
  },
  {
    'code': 'ZA',
    'pays': 'Afrique du Sud',
    'reponses': ['Pretoria', 'Le Cap', 'Bloemfontein', 'Johannesburg'],
    'capitale': 'Pretoria',
  },
  {
    'code': 'SS',
    'pays': 'Soudan du Sud',
    'reponses': ['Djouba', 'Wau', 'Malakal', 'Yei'],
    'capitale': 'Djouba',
  },
  {
    'code': 'SD',
    'pays': 'Soudan',
    'reponses': ['Khartoum', 'Omdurman', 'Kassala', 'Nyala'],
    'capitale': 'Khartoum',
  },
  {
    'code': 'SZ',
    'pays': 'Eswatini',
    'reponses': ['Mbabane', 'Lobamba', 'Manzini', 'Big Bend'],
    'capitale': 'Mbabane',
  },
  {
    'code': 'TZ',
    'pays': 'Tanzanie',
    'reponses': ['Dodoma', 'Dar es Salaam', 'Mwanza', 'Arusha'],
    'capitale': 'Dodoma',
  },
  {
    'code': 'TG',
    'pays': 'Togo',
    'reponses': ['Lomé', 'Sokodé', 'Kara', 'Kpalimé'],
    'capitale': 'Lomé',
  },
  {
    'code': 'TN',
    'pays': 'Tunisie',
    'reponses': ['Tunis', 'Sfax', 'Sousse', 'Kairouan'],
    'capitale': 'Tunis',
  },
  {
    'code': 'UG',
    'pays': 'Ouganda',
    'reponses': ['Kampala', 'Gulu', 'Lira', 'Mbale'],
    'capitale': 'Kampala',
  },
  {
    'code': 'ZM',
    'pays': 'Zambie',
    'reponses': ['Lusaka', 'Ndola', 'Kitwe', 'Kabwe'],
    'capitale': 'Lusaka',
  },
  {
    'code': 'ZW',
    'pays': 'Zimbabwe',
    'reponses': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'],
    'capitale': 'Harare',
  },
  {
    'code': 'KM',
    'pays': 'Union des Comores',
    'reponses': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni'],
    'capitale': 'Moroni',
  },
  //-------------------------
  {
    'code': 'AL',
    'pays': 'Albanie',
    'reponses': ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'],
    'capitale': 'Tirana',
  },
  {
    'code': 'DE',
    'pays': 'Allemagne',
    'reponses': ['Berlin', 'Hambourg', 'Munich', 'Cologne'],
    'capitale': 'Berlin',
  },
  {
    'code': 'AD',
    'pays': 'Andorre',
    'reponses': [
      'Andorre-la-Vieille',
      'Escaldes-Engordany',
      'Encamp',
      'Sant Julià de Lòria'
    ],
    'capitale': 'Andorre-la-Vieille',
  },
  {
    'code': 'AT',
    'pays': 'Autriche',
    'reponses': ['Vienne', 'Graz', 'Linz', 'Salzbourg'],
    'capitale': 'Vienne',
  },
  {
    'code': 'BE',
    'pays': 'Belgique',
    'reponses': ['Bruxelles', 'Anvers', 'Gand', 'Charleroi'],
    'capitale': 'Bruxelles',
  },
  {
    'code': 'BY',
    'pays': 'Biélorussie',
    'reponses': ['Minsk', 'Hrodna', 'Brest', 'Moguilev'],
    'capitale': 'Minsk',
  },
  {
    'code': 'BA',
    'pays': 'Bosnie-Herzégovine',
    'reponses': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Mostar'],
    'capitale': 'Sarajevo',
  },
  {
    'code': 'BG',
    'pays': 'Bulgarie',
    'reponses': ['Sofia', 'Plovdiv', 'Varna', 'Bourgas'],
    'capitale': 'Sofia',
  },
  {
    'code': 'CY',
    'pays': 'Chypre',
    'reponses': ['Nicosie', 'Limassol', 'Larnaca', 'Paphos'],
    'capitale': 'Nicosie',
  },
  {
    'code': 'HR',
    'pays': 'Croatie',
    'reponses': ['Zagreb', 'Split', 'Rijeka', 'Osijek'],
    'capitale': 'Zagreb',
  },
  {
    'code': 'DK',
    'pays': 'Danemark',
    'reponses': ['Copenhague', 'Aarhus', 'Odense', 'Aalborg'],
    'capitale': 'Copenhague',
  },
  {
    'code': 'ES',
    'pays': 'Espagne',
    'reponses': ['Madrid', 'Barcelone', 'Valence', 'Séville'],
    'capitale': 'Madrid',
  },
  {
    'code': 'EE',
    'pays': 'Estonie',
    'reponses': ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
    'capitale': 'Tallinn',
  },
  {
    'code': 'FI',
    'pays': 'Finlande',
    'reponses': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'],
    'capitale': 'Helsinki',
  },
  {
    'code': 'FR',
    'pays': 'France',
    'reponses': ['Paris', 'Marseille', 'Lyon', 'Toulouse'],
    'capitale': 'Paris',
  },
  {
    'code': 'GR',
    'pays': 'Grèce',
    'reponses': ['Athènes', 'Thessalonique', 'Patras', 'Héraklion'],
    'capitale': 'Athènes',
  },
  {
    'code': 'HU',
    'pays': 'Hongrie',
    'reponses': ['Budapest', 'Debrecen', 'Miskolc', 'Szeged'],
    'capitale': 'Budapest',
  },
  {
    'code': 'IE',
    'pays': 'Irlande',
    'reponses': ['Dublin', 'Cork', 'Galway', 'Limerick'],
    'capitale': 'Dublin',
  },
  {
    'code': 'IS',
    'pays': 'Islande',
    'reponses': ['Reykjavik', 'Kopavogur', 'Hafnarfjordur', 'Akureyri'],
    'capitale': 'Reykjavik',
  },
  {
    'code': 'IT',
    'pays': 'Italie',
    'reponses': ['Rome', 'Milan', 'Naples', 'Turin'],
    'capitale': 'Rome',
  },
  {
    'code': 'KZ',
    'pays': 'Kazakhstan',
    'reponses': ['Noursoultan', 'Almaty', 'Chymkent', 'Shymkent'],
    'capitale': 'Noursoultan',
  },
  {
    'code': 'XK',
    'pays': 'Kosovo',
    'reponses': ['Pristina', 'Mitrovica', 'Prizren', 'Peja'],
    'capitale': 'Pristina',
  },
  {
    'code': 'LV',
    'pays': 'Lettonie',
    'reponses': ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava'],
    'capitale': 'Riga',
  },
  {
    'code': 'LI',
    'pays': 'Liechtenstein',
    'reponses': ['Vaduz', 'Schaan', 'Triesen', 'Balzers'],
    'capitale': 'Vaduz',
  },
  {
    'code': 'LT',
    'pays': 'Lituanie',
    'reponses': ['Vilnius', 'Kaunas', 'Klaipeda', 'Šiauliai'],
    'capitale': 'Vilnius',
  },
  {
    'code': 'LU',
    'pays': 'Luxembourg',
    'reponses': ['Luxembourg', 'Esch-sur-Alzette', 'Dudelange', 'Differdange'],
    'capitale': 'Luxembourg',
  },
  {
    'code': 'MK',
    'pays': 'Macédoine du Nord',
    'reponses': ['Skopje', 'Bitola', 'Kumanovo', 'Prilep'],
    'capitale': 'Skopje',
  },
  {
    'code': 'MT',
    'pays': 'Malte',
    'reponses': ['La Valette', 'Birkirkara', 'Mosta', 'Qormi'],
    'capitale': 'La Valette',
  },
  {
    'code': 'MD',
    'pays': 'Moldavie',
    'reponses': ['Chișinău', 'Tiraspol', 'Bălți', 'Bender'],
    'capitale': 'Chișinău',
  },
  {
    'code': 'MC',
    'pays': 'Monaco',
    'reponses': ['Monaco', 'Monte-Carlo', 'La Condamine', 'Fontvieille'],
    'capitale': 'Monaco',
  },
  {
    'code': 'ME',
    'pays': 'Monténégro',
    'reponses': ['Podgorica', 'Nikšić', 'Herceg Novi', 'Bar'],
    'capitale': 'Podgorica',
  },
  {
    'code': 'NO',
    'pays': 'Norvège',
    'reponses': ['Oslo', 'Bergen', 'Stavanger', 'Trondheim'],
    'capitale': 'Oslo',
  },
  {
    'code': 'NL',
    'pays': 'Pays-Bas',
    'reponses': ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht'],
    'capitale': 'Amsterdam',
  },
  {
    'code': 'PL',
    'pays': 'Pologne',
    'reponses': ['Varsovie', 'Cracovie', 'Łódź', 'Wrocław'],
    'capitale': 'Varsovie',
  },
  {
    'code': 'PT',
    'pays': 'Portugal',
    'reponses': ['Lisbonne', 'Porto', 'Vila Nova de Gaia', 'Amadora'],
    'capitale': 'Lisbonne',
  },
  {
    'code': 'CZ',
    'pays': 'République tchèque',
    'reponses': ['Prague', 'Brno', 'Ostrava', 'Plzeň'],
    'capitale': 'Prague',
  },
  {
    'code': 'RO',
    'pays': 'Roumanie',
    'reponses': ['Bucarest', 'Cluj-Napoca', 'Timișoara', 'Iași'],
    'capitale': 'Bucarest',
  },
  {
    'code': 'GB',
    'pays': 'Royaume-Uni',
    'reponses': ['Londres', 'Birmingham', 'Manchester', 'Glasgow'],
    'capitale': 'Londres',
  },
  {
    'code': 'RU',
    'pays': 'Russie',
    'reponses': [
      'Moscou',
      'Saint-Pétersbourg',
      'Novossibirsk',
      'Iekaterinbourg'
    ],
    'capitale': 'Moscou',
  },
  {
    'code': 'SM',
    'pays': 'Saint-Marin',
    'reponses': ['Saint-Marin', 'Serravalle', 'Domagnano', 'Borgo Maggiore'],
    'capitale': 'Saint-Marin',
  },
  {
    'code': 'RS',
    'pays': 'Serbie',
    'reponses': ['Belgrade', 'Niš', 'Novi Sad', 'Kragujevac'],
    'capitale': 'Belgrade',
  },
  {
    'code': 'SK',
    'pays': 'Slovaquie',
    'reponses': ['Bratislava', 'Košice', 'Prešov', 'Žilina'],
    'capitale': 'Bratislava',
  },
  {
    'code': 'SI',
    'pays': 'Slovénie',
    'reponses': ['Ljubljana', 'Maribor', 'Celje', 'Kranj'],
    'capitale': 'Ljubljana',
  },
  {
    'code': 'SE',
    'pays': 'Suède',
    'reponses': ['Stockholm', 'Göteborg', 'Malmö', 'Uppsala'],
    'capitale': 'Stockholm',
  },
  {
    'code': 'CH',
    'pays': 'Suisse',
    'reponses': ['Berne', 'Zurich', 'Genève', 'Bâle'],
    'capitale': 'Berne',
  },
  {
    'code': 'UA',
    'pays': 'Ukraine',
    'reponses': ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro'],
    'capitale': 'Kiev',
  },
  {
    'code': 'VA',
    'pays': 'Vatican',
    'reponses': ['Cité du Vatican'],
    'capitale': 'Cité du Vatican',
  },
  //-----------------
  {
    'code': 'AG',
    'pays': 'Antigua-et-Barbuda',
    'reponses': ['Saint John\'s', 'All Saints', 'Liberta', 'Bolans'],
    'capitale': 'Saint John\'s',
  },
  {
    'code': 'AR',
    'pays': 'Argentine',
    'reponses': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'],
    'capitale': 'Buenos Aires',
  },
  {
    'code': 'BS',
    'pays': 'Bahamas',
    'reponses': ['Nassau', 'Freeport', 'Lucaya', 'West End'],
    'capitale': 'Nassau',
  },
  {
    'code': 'BB',
    'pays': 'Barbade',
    'reponses': ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba'],
    'capitale': 'Bridgetown',
  },
  {
    'code': 'BZ',
    'pays': 'Belize',
    'reponses': ['Belmopan', 'Belize City', 'San Ignacio', 'Orange Walk'],
    'capitale': 'Belmopan',
  },
  {
    'code': 'BO',
    'pays': 'Bolivie',
    'reponses': ['La Paz', 'Sucre', 'Cochabamba', 'Oruro'],
    'capitale': 'La Paz',
  },
  {
    'code': 'BR',
    'pays': 'Brésil',
    'reponses': ['Brasília', 'São Paulo', 'Rio de Janeiro', 'Salvador'],
    'capitale': 'Brasília',
  },
  {
    'code': 'CA',
    'pays': 'Canada',
    'reponses': ['Ottawa', 'Toronto', 'Montréal', 'Vancouver'],
    'capitale': 'Ottawa',
  },
  {
    'code': 'CL',
    'pays': 'Chili',
    'reponses': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena'],
    'capitale': 'Santiago',
  },
  {
    'code': 'CO',
    'pays': 'Colombie',
    'reponses': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'],
    'capitale': 'Bogotá',
  },
  {
    'code': 'CR',
    'pays': 'Costa Rica',
    'reponses': ['San José', 'Limon', 'San Francisco', 'Alajuela'],
    'capitale': 'San José',
  },
  {
    'code': 'CU',
    'pays': 'Cuba',
    'reponses': ['La Havane', 'Santiago de Cuba', 'Camagüey', 'Holguín'],
    'capitale': 'La Havane',
  },
  {
    'code': 'DO',
    'pays': 'République dominicaine',
    'reponses': [
      'Saint-Domingue',
      'Santiago de los Caballeros',
      'Santo Domingo Este',
      'San Pedro de Macorís'
    ],
    'capitale': 'Saint-Domingue',
  },
  {
    'code': 'DM',
    'pays': 'Dominique',
    'reponses': ['Roseau', 'Portsmouth', 'Marigot', 'Berekua'],
    'capitale': 'Roseau',
  },
  {
    'code': 'EC',
    'pays': 'Équateur',
    'reponses': ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo'],
    'capitale': 'Quito',
  },
  {
    'code': 'US',
    'pays': 'États-Unis',
    'reponses': ['Washington', 'New York', 'Los Angeles', 'Chicago'],
    'capitale': 'Washington',
  },
  {
    'code': 'GD',
    'pays': 'Grenade',
    'reponses': ['Saint George\'s', 'Gouyave', 'Grenville', 'Victoria'],
    'capitale': 'Saint George\'s',
  },
  {
    'code': 'GT',
    'pays': 'Guatemala',
    'reponses': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'],
    'capitale': 'Guatemala City',
  },
  {
    'code': 'GY',
    'pays': 'Guyana',
    'reponses': ['Georgetown', 'Linden', 'New Amsterdam', 'Bartica'],
    'capitale': 'Georgetown',
  },
  {
    'code': 'HT',
    'pays': 'Haïti',
    'reponses': ['Port-au-Prince', 'Cap-Haïtien', 'Carrefour', 'Delmas'],
    'capitale': 'Port-au-Prince',
  },
  {
    'code': 'HN',
    'pays': 'Honduras',
    'reponses': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'],
    'capitale': 'Tegucigalpa',
  },
  {
    'code': 'JM',
    'pays': 'Jamaïque',
    'reponses': ['Kingston', 'New Kingston', 'Spanish Town', 'Montego Bay'],
    'capitale': 'Kingston',
  },
  {
    'code': 'MX',
    'pays': 'Mexique',
    'reponses': ['Mexico', 'Guadalajara', 'Monterrey', 'Puebla'],
    'capitale': 'Mexico',
  },
  {
    'code': 'NI',
    'pays': 'Nicaragua',
    'reponses': ['Managua', 'León', 'Masaya', 'Matagalpa'],
    'capitale': 'Managua',
  },
  {
    'code': 'PA',
    'pays': 'Panama',
    'reponses': ['Panama City', 'San Miguelito', 'Tocumen', 'David'],
    'capitale': 'Panama City',
  },
  {
    'code': 'PY',
    'pays': 'Paraguay',
    'reponses': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Lambaré'],
    'capitale': 'Asunción',
  },
  {
    'code': 'PE',
    'pays': 'Pérou',
    'reponses': ['Lima', 'Arequipa', 'Callao', 'Trujillo'],
    'capitale': 'Lima',
  },
  {
    'code': 'KN',
    'pays': 'Saint-Christophe-et-Niévès',
    'reponses': [
      'Basseterre',
      'Charlestown',
      'Dieppe Bay Town',
      'Half Way Tree'
    ],
    'capitale': 'Basseterre',
  },
  {
    'code': 'LC',
    'pays': 'Sainte-Lucie',
    'reponses': ['Castries', 'Vieux Fort', 'Micoud', 'Soufrière'],
    'capitale': 'Castries',
  },
  {
    'code': 'VC',
    'pays': 'Saint-Vincent-et-les-Grenadines',
    'reponses': ['Kingstown', 'Kingstown Park', 'Arnos Vale', 'Port Elizabeth'],
    'capitale': 'Kingstown',
  },
  {
    'code': 'SV',
    'pays': 'Salvador',
    'reponses': ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel'],
    'capitale': 'San Salvador',
  },
  {
    'code': 'SR',
    'pays': 'Suriname',
    'reponses': ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo'],
    'capitale': 'Paramaribo',
  },
  {
    'code': 'TT',
    'pays': 'Trinité-et-Tobago',
    'reponses': ['Port of Spain', 'Chaguanas', 'San Fernando', 'Arima'],
    'capitale': 'Port of Spain',
  },
  {
    'code': 'UY',
    'pays': 'Uruguay',
    'reponses': ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú'],
    'capitale': 'Montevideo',
  },
  {
    'code': 'VE',
    'pays': 'Venezuela',
    'reponses': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto'],
    'capitale': 'Caracas',
  },
  //-----
  {
    'code': 'AF',
    'pays': 'Afghanistan',
    'reponses': ['Kaboul', 'Hérat', 'Mazar-e-Charif', 'Kandahar'],
    'capitale': 'Kaboul',
  },
  {
    'code': 'SA',
    'pays': 'Arabie saoudite',
    'reponses': ['Riyad', 'Djeddah', 'Médine', 'La Mecque'],
    'capitale': 'Riyad',
  },
  {
    'code': 'AM',
    'pays': 'Arménie',
    'reponses': ['Erevan', 'Gyumri', 'Vanadzor', 'Vagharshapat'],
    'capitale': 'Erevan',
  },
  {
    'code': 'AZ',
    'pays': 'Azerbaïdjan',
    'reponses': ['Bakou', 'Gandja', 'Sumqayit', 'Mingachevir'],
    'capitale': 'Bakou',
  },
  {
    'code': 'BH',
    'pays': 'Bahreïn',
    'reponses': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
    'capitale': 'Manama',
  },
  {
    'code': 'BD',
    'pays': 'Bangladesh',
    'reponses': ['Dacca', 'Chittagong', 'Khulna', 'Rajshahi'],
    'capitale': 'Dacca',
  },
  {
    'code': 'BT',
    'pays': 'Bhoutan',
    'reponses': ['Thimphou', 'Phuntsholing', 'Paro', 'Punakha'],
    'capitale': 'Thimphou',
  },
  {
    'code': 'MM',
    'pays': 'Birmanie',
    'reponses': ['Naypyidaw', 'Rangoun', 'Mandalay', 'Moulmein'],
    'capitale': 'Naypyidaw',
  },
  {
    'code': 'BN',
    'pays': 'Brunei',
    'reponses': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'],
    'capitale': 'Bandar Seri Begawan',
  },
  {
    'code': 'KH',
    'pays': 'Cambodge',
    'reponses': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'],
    'capitale': 'Phnom Penh',
  },
  {
    'code': 'CN',
    'pays': 'Chine',
    'reponses': ['Pékin', 'Shanghai', 'Canton', 'Shenzhen'],
    'capitale': 'Pékin',
  },
  {
    'code': 'CY',
    'pays': 'Chypre',
    'reponses': ['Nicosie', 'Limassol', 'Larnaca', 'Paphos'],
    'capitale': 'Nicosie',
  },
  {
    'code': 'KP',
    'pays': 'Corée du Nord',
    'reponses': ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo'],
    'capitale': 'Pyongyang',
  },
  {
    'code': 'KR',
    'pays': 'Corée du Sud',
    'reponses': ['Séoul', 'Busan', 'Incheon', 'Daegu'],
    'capitale': 'Séoul',
  },
  {
    'code': 'AE',
    'pays': 'Émirats arabes unis',
    'reponses': ['Abou Dabi', 'Dubai', 'Charjah', 'Ajman'],
    'capitale': 'Abou Dabi',
  },
  {
    'code': 'GE',
    'pays': 'Géorgie',
    'reponses': ['Tbilissi', 'Koutaïssi', 'Batoumi', 'Soukhoumi'],
    'capitale': 'Tbilissi',
  },
  {
    'code': 'IN',
    'pays': 'Inde',
    'reponses': ['New Delhi', 'Mumbai', 'Bangalore', 'Chennai'],
    'capitale': 'New Delhi',
  },
  {
    'code': 'ID',
    'pays': 'Indonésie',
    'reponses': ['Jakarta', 'Surabaya', 'Bandung', 'Medan'],
    'capitale': 'Jakarta',
  },
  {
    'code': 'IR',
    'pays': 'Iran',
    'reponses': ['Téhéran', 'Mashhad', 'Ispahan', 'Karaj'],
    'capitale': 'Téhéran',
  },
  {
    'code': 'IQ',
    'pays': 'Irak',
    'reponses': ['Bagdad', 'Bassorah', 'Irbil', 'Najaf'],
    'capitale': 'Bagdad',
  },
  {
    'code': 'IL',
    'pays': 'Israël',
    'reponses': ['Jérusalem', 'Tel Aviv', 'Haïfa', 'Rishon LeZion'],
    'capitale': 'Jérusalem',
  },
  {
    'code': 'JP',
    'pays': 'Japon',
    'reponses': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya'],
    'capitale': 'Tokyo',
  },
  {
    'code': 'JO',
    'pays': 'Jordanie',
    'reponses': ['Amman', 'Zarqa', 'Irbid', 'Russeifa'],
    'capitale': 'Amman',
  },
  {
    'code': 'KZ',
    'pays': 'Kazakhstan',
    'reponses': ['Noursoultan', 'Almaty', 'Chymkent', 'Shymkent'],
    'capitale': 'Noursoultan',
  },
  {
    'code': 'KG',
    'pays': 'Kirghizistan',
    'reponses': ['Bichkek', 'Osh', 'Jalal-Abad', 'Karakol'],
    'capitale': 'Bichkek',
  },
  {
    'code': 'KW',
    'pays': 'Koweït',
    'reponses': ['Koweït', 'Al-Ahmadi', 'Hawalli', 'Mubarak Al-Kabeer'],
    'capitale': 'Koweït',
  },
  {
    'code': 'LA',
    'pays': 'Laos',
    'reponses': ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'],
    'capitale': 'Vientiane',
  },
  {
    'code': 'LB',
    'pays': 'Liban',
    'reponses': ['Beyrouth', 'Tripoli', 'Sidon', 'Tyre'],
    'capitale': 'Beyrouth',
  },
  {
    'code': 'MY',
    'pays': 'Malaisie',
    'reponses': ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam'],
    'capitale': 'Kuala Lumpur',
  },
  {
    'code': 'MV',
    'pays': 'Maldives',
    'reponses': ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi'],
    'capitale': 'Malé',
  },
  {
    'code': 'MN',
    'pays': 'Mongolie',
    'reponses': ['Oulan-Bator', 'Darkhan', 'Erdenet', 'Choibalsan'],
    'capitale': 'Oulan-Bator',
  },
  {
    'code': 'NP',
    'pays': 'Népal',
    'reponses': ['Katmandou', 'Pokhara', 'Patan', 'Biratnagar'],
    'capitale': 'Katmandou',
  },
  {
    'code': 'OM',
    'pays': 'Oman',
    'reponses': ['Mascate', 'Salalah', 'Suhar', 'Nizwa'],
    'capitale': 'Mascate',
  },
  {
    'code': 'UZ',
    'pays': 'Ouzbékistan',
    'reponses': ['Tachkent', 'Namangan', 'Andijan', 'Samarkand'],
    'capitale': 'Tachkent',
  },
  {
    'code': 'PK',
    'pays': 'Pakistan',
    'reponses': ['Islamabad', 'Karachi', 'Lahore', 'Faisalabad'],
    'capitale': 'Islamabad',
  },
  {
    'code': 'PS',
    'pays': 'Palestine',
    'reponses': ['Jérusalem-Est', 'Gaza', 'Naplouse', 'Rafah'],
    'capitale': 'Jérusalem-Est',
  },
  {
    'code': 'PH',
    'pays': 'Philippines',
    'reponses': ['Manille', 'Quezon City', 'Davao', 'Cebu City'],
    'capitale': 'Manille',
  },
  {
    'code': 'QA',
    'pays': 'Qatar',
    'reponses': ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah'],
    'capitale': 'Doha',
  },
  {
    'code': 'SG',
    'pays': 'Singapour',
    'reponses': ['Singapour', 'Woodlands', 'Jurong West', 'Tampines'],
    'capitale': 'Singapour',
  },
  {
    'code': 'LK',
    'pays': 'Sri Lanka',
    'reponses': ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Jaffna'],
    'capitale': 'Colombo',
  },
  {
    'code': 'SY',
    'pays': 'Syrie',
    'reponses': ['Damas', 'Alep', 'Homs', 'Hama'],
    'capitale': 'Damas',
  },
  {
    'code': 'TJ',
    'pays': 'Tadjikistan',
    'reponses': ['Douchanbé', 'Khoudjand', 'Qurghonteppa', 'Kulob'],
    'capitale': 'Douchanbé',
  },
  {
    'code': 'TW',
    'pays': 'Taïwan',
    'reponses': ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan'],
    'capitale': 'Taipei',
  },
  {
    'code': 'TH',
    'pays': 'Thaïlande',
    'reponses': ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai'],
    'capitale': 'Bangkok',
  },
  {
    'code': 'TL',
    'pays': 'Timor oriental',
    'reponses': ['Dili', 'Same', 'Baucau', 'Liquiçá'],
    'capitale': 'Dili',
  },
  {
    'code': 'TM',
    'pays': 'Turkménistan',
    'reponses': ['Achgabat', 'Daşoguz', 'Mary', 'Türkmenabat'],
    'capitale': 'Achgabat',
  },
  {
    'code': 'TR',
    'pays': 'Turquie',
    'reponses': ['Ankara', 'Istanbul', 'Izmir', 'Bursa'],
    'capitale': 'Ankara',
  },
  {
    'code': 'VN',
    'pays': 'Viêt Nam',
    'reponses': ['Hanoï', 'Hô Chi Minh-Ville', 'Hải Phòng', 'Cần Thơ'],
    'capitale': 'Hanoï',
  },
  {
    'code': 'YE',
    'pays': 'Yémen',
    'reponses': ['Sanaa', 'Aden', 'Taëz', 'Al Hudaydah'],
    'capitale': 'Sanaa',
  },
  //------------------
  {
    'code': 'AU',
    'pays': 'Australie',
    'reponses': ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    'capitale': 'Canberra',
  },
  {
    'code': 'FJ',
    'pays': 'Fidji',
    'reponses': ['Suva', 'Lautoka', 'Nadi', 'Labasa'],
    'capitale': 'Suva',
  },
  {
    'code': 'MH',
    'pays': 'Îles Marshall',
    'reponses': ['Majuro', 'Ebeye', 'Jabor', 'Laura'],
    'capitale': 'Majuro',
  },
  {
    'code': 'KI',
    'pays': 'Kiribati',
    'reponses': ['Tarawa', 'Betio', 'Bikenibeu', 'Teaoraereke'],
    'capitale': 'Tarawa',
  },
  {
    'code': 'FM',
    'pays': 'Micronésie',
    'reponses': ['Palikir', 'Weno', 'Colonia', 'Tofol'],
    'capitale': 'Palikir',
  },
  {
    'code': 'NR',
    'pays': 'Nauru',
    'reponses': ['Yaren', 'Denigomodu', 'Meneng', 'Buada'],
    'capitale': 'Yaren',
  },
  {
    'code': 'NZ',
    'pays': 'Nouvelle-Zélande',
    'reponses': ['Wellington', 'Auckland', 'Christchurch', 'Hamilton'],
    'capitale': 'Wellington',
  },
  {
    'code': 'PW',
    'pays': 'Palaos',
    'reponses': ['Ngerulmud', 'Koror', 'Airai', 'Melekeok'],
    'capitale': 'Ngerulmud',
  },
  {
    'code': 'PG',
    'pays': 'Papouasie-Nouvelle-Guinée',
    'reponses': ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang'],
    'capitale': 'Port Moresby',
  },
  {
    'code': 'SB',
    'pays': 'Salomon',
    'reponses': ['Honiara', 'Gizo', 'Auki', 'Kirakira'],
    'capitale': 'Honiara',
  },
  {
    'code': 'WS',
    'pays': 'Samoa',
    'reponses': ['Apia', 'Asau', 'Mulifanua', 'Faleula'],
    'capitale': 'Apia',
  },
  {
    'code': 'TO',
    'pays': 'Tonga',
    'reponses': ['Nukuʻalofa', 'Neiafu', 'Vaini', 'Haveluloto'],
    'capitale': 'Nukuʻalofa',
  },
  {
    'code': 'TV',
    'pays': 'Tuvalu',
    'reponses': ['Funafuti', 'Fongafale', 'Vaiaku', 'Alapi'],
    'capitale': 'Funafuti',
  },
  {
    'code': 'VU',
    'pays': 'Vanuatu',
    'reponses': ['Port-Vila', 'Luganville', 'Norsup', 'Sola'],
    'capitale': 'Port-Vila',
  },
];

const Afrique = [
  {
    'code': 'DZ',
    'pays': 'Algérie',
    'reponses': ['Alger', 'Oran', 'Constantine', 'Annaba'],
    'capitale': 'Alger',
  },
  {
    'code': 'AO',
    'pays': 'Angola',
    'reponses': ['Luanda', 'Lubango', 'Cabinda', 'Benguela'],
    'capitale': 'Luanda',
  },
  {
    'code': 'BJ',
    'pays': 'Bénin',
    'reponses': ['Porto-Novo', 'Cotonou', 'Parakou', 'Abomey'],
    'capitale': 'Porto-Novo',
  },
  {
    'code': 'BW',
    'pays': 'Botswana',
    'reponses': ['Gaborone', 'Francistown', 'Maun', 'Serowe'],
    'capitale': 'Gaborone',
  },
  {
    'code': 'BF',
    'pays': 'Burkina Faso',
    'reponses': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora'],
    'capitale': 'Ouagadougou',
  },
  {
    'code': 'BI',
    'pays': 'Burundi',
    'reponses': ['Bujumbura', 'Gitega', 'Ngozi', 'Ruyigi'],
    'capitale': 'Bujumbura',
  },
  {
    'code': 'CV',
    'pays': 'Cabo Verde',
    'reponses': ['Praia', 'Mindelo', 'Santa Maria', 'Assomada'],
    'capitale': 'Praia',
  },
  {
    'code': 'CM',
    'pays': 'Cameroun',
    'reponses': ['Yaoundé', 'Douala', 'Bamenda', 'Bafoussam'],
    'capitale': 'Yaoundé',
  },
  {
    'code': 'CF',
    'pays': 'République centrafricaine',
    'reponses': ['Bangui', 'Bimbo', 'Berbérati', 'Carnot'],
    'capitale': 'Bangui',
  },
  {
    'code': 'TD',
    'pays': 'Tchad',
    'reponses': ['N\'Djamena', 'Moundou', 'Sarh', 'Abeche'],
    'capitale': 'N\'Djamena',
  },
  {
    'code': 'KM',
    'pays': 'Comores',
    'reponses': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni'],
    'capitale': 'Moroni',
  },
  {
    'code': 'CD',
    'pays': 'République démocratique du Congo',
    'reponses': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga'],
    'capitale': 'Kinshasa',
  },
  {
    'code': 'DJ',
    'pays': 'Djibouti',
    'reponses': ['Djibouti', 'Ali Sabieh', 'Tadjoura', 'Obock'],
    'capitale': 'Djibouti',
  },
  {
    'code': 'EG',
    'pays': 'Égypte',
    'reponses': ['Le Caire', 'Alexandrie', 'Gizeh', 'Port-Saïd'],
    'capitale': 'Le Caire',
  },
  {
    'code': 'GQ',
    'pays': 'Guinée équatoriale',
    'reponses': ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe'],
    'capitale': 'Malabo',
  },
  {
    'code': 'ER',
    'pays': 'Érythrée',
    'reponses': ['Asmara', 'Keren', 'Massawa', 'Assab'],
    'capitale': 'Asmara',
  },
  {
    'code': 'ET',
    'pays': 'Éthiopie',
    'reponses': ['Addis-Abeba', 'Dire Dawa', 'Nakfa', 'Bahir Dar'],
    'capitale': 'Addis-Abeba',
  },
  {
    'code': 'GA',
    'pays': 'Gabon',
    'reponses': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem'],
    'capitale': 'Libreville',
  },
  {
    'code': 'GM',
    'pays': 'Gambie',
    'reponses': ['Banjul', 'Serekunda', 'Brikama', 'Bakau'],
    'capitale': 'Banjul',
  },
  {
    'code': 'GH',
    'pays': 'Ghana',
    'reponses': ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi'],
    'capitale': 'Accra',
  },
  {
    'code': 'GN',
    'pays': 'Guinée',
    'reponses': ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia'],
    'capitale': 'Conakry',
  },
  {
    'code': 'GW',
    'pays': 'Guinée-Bissau',
    'reponses': ['Bissau', 'Bolama', 'Gabú', 'Bafatá'],
    'capitale': 'Bissau',
  },
  {
    'code': 'CI',
    'pays': 'Côte d\'Ivoire',
    'reponses': ['Yamoussoukro', 'Abidjan', 'Bouaké', 'Daloa'],
    'capitale': 'Yamoussoukro',
  },
  {
    'code': 'KE',
    'pays': 'Kenya',
    'reponses': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
    'capitale': 'Nairobi',
  },
  {
    'code': 'LS',
    'pays': 'Lesotho',
    'reponses': ['Maseru', 'Teyateyaneng', 'Leribe', 'Mafeteng'],
    'capitale': 'Maseru',
  },
  {
    'code': 'LR',
    'pays': 'Libéria',
    'reponses': ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville'],
    'capitale': 'Monrovia',
  },
  {
    'code': 'LY',
    'pays': 'Libye',
    'reponses': ['Tripoli', 'Benghazi', 'Misrata', 'Sirte'],
    'capitale': 'Tripoli',
  },
  {
    'code': 'MG',
    'pays': 'Madagascar',
    'reponses': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa'],
    'capitale': 'Antananarivo',
  },
  {
    'code': 'MW',
    'pays': 'Malawi',
    'reponses': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
    'capitale': 'Lilongwe',
  },
  {
    'code': 'ML',
    'pays': 'Mali',
    'reponses': ['Bamako', 'Sikasso', 'Ségou', 'Mopti'],
    'capitale': 'Bamako',
  },
  {
    'code': 'MR',
    'pays': 'Mauritanie',
    'reponses': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Zouérat'],
    'capitale': 'Nouakchott',
  },
  {
    'code': 'MU',
    'pays': 'Maurice',
    'reponses': [
      'Port-Louis',
      'Beau Bassin-Rose Hill',
      'Vacoas-Phoenix',
      'Curepipe'
    ],
    'capitale': 'Port-Louis',
  },
  {
    'code': 'MA',
    'pays': 'Maroc',
    'reponses': ['Rabat', 'Casablanca', 'Fès', 'Marrakech'],
    'capitale': 'Rabat',
  },
  {
    'code': 'MZ',
    'pays': 'Mozambique',
    'reponses': ['Maputo', 'Matola', 'Beira', 'Nampula'],
    'capitale': 'Maputo',
  },
  {
    'code': 'NA',
    'pays': 'Namibie',
    'reponses': ['Windhoek', 'Rundu', 'Walvis Bay', 'Oshakati'],
    'capitale': 'Windhoek',
  },
  {
    'code': 'NE',
    'pays': 'Niger',
    'reponses': ['Niamey', 'Zinder', 'Maradi', 'Agadez'],
    'capitale': 'Niamey',
  },
  {
    'code': 'NG',
    'pays': 'Nigeria',
    'reponses': ['Abuja', 'Lagos', 'Kano', 'Ibadan'],
    'capitale': 'Abuja',
  },
  {
    'code': 'RW',
    'pays': 'Rwanda',
    'reponses': ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'],
    'capitale': 'Kigali',
  },
  {
    'code': 'ST',
    'pays': 'Sao Tomé-et-Principe',
    'reponses': ['São Tomé', 'Neves', 'Trindade', 'Santana'],
    'capitale': 'São Tomé',
  },
  {
    'code': 'SN',
    'pays': 'Sénégal',
    'reponses': ['Dakar', 'Thiès', 'Kaolack', 'Ziguinchor'],
    'capitale': 'Dakar',
  },
  {
    'code': 'SC',
    'pays': 'Seychelles',
    'reponses': ['Victoria', 'Anse Boileau', 'Beau Vallon', 'Cascade'],
    'capitale': 'Victoria',
  },
  {
    'code': 'SL',
    'pays': 'Sierra Leone',
    'reponses': ['Freetown', 'Bo', 'Kenema', 'Makeni'],
    'capitale': 'Freetown',
  },
  {
    'code': 'SO',
    'pays': 'Somalie',
    'reponses': ['Mogadiscio', 'Hargeisa', 'Bosaso', 'Kismayo'],
    'capitale': 'Mogadiscio',
  },
  {
    'code': 'ZA',
    'pays': 'Afrique du Sud',
    'reponses': ['Pretoria', 'Le Cap', 'Bloemfontein', 'Johannesburg'],
    'capitale': 'Pretoria',
  },
  {
    'code': 'SS',
    'pays': 'Soudan du Sud',
    'reponses': ['Djouba', 'Wau', 'Malakal', 'Yei'],
    'capitale': 'Djouba',
  },
  {
    'code': 'SD',
    'pays': 'Soudan',
    'reponses': ['Khartoum', 'Omdurman', 'Kassala', 'Nyala'],
    'capitale': 'Khartoum',
  },
  {
    'code': 'SZ',
    'pays': 'Eswatini',
    'reponses': ['Mbabane', 'Lobamba', 'Manzini', 'Big Bend'],
    'capitale': 'Mbabane',
  },
  {
    'code': 'TZ',
    'pays': 'Tanzanie',
    'reponses': ['Dodoma', 'Dar es Salaam', 'Mwanza', 'Arusha'],
    'capitale': 'Dodoma',
  },
  {
    'code': 'TG',
    'pays': 'Togo',
    'reponses': ['Lomé', 'Sokodé', 'Kara', 'Kpalimé'],
    'capitale': 'Lomé',
  },
  {
    'code': 'TN',
    'pays': 'Tunisie',
    'reponses': ['Tunis', 'Sfax', 'Sousse', 'Kairouan'],
    'capitale': 'Tunis',
  },
  {
    'code': 'UG',
    'pays': 'Ouganda',
    'reponses': ['Kampala', 'Gulu', 'Lira', 'Mbale'],
    'capitale': 'Kampala',
  },
  {
    'code': 'ZM',
    'pays': 'Zambie',
    'reponses': ['Lusaka', 'Ndola', 'Kitwe', 'Kabwe'],
    'capitale': 'Lusaka',
  },
  {
    'code': 'ZW',
    'pays': 'Zimbabwe',
    'reponses': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'],
    'capitale': 'Harare',
  },
  {
    'code': 'KM',
    'pays': 'Union des Comores',
    'reponses': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni'],
    'capitale': 'Moroni',
  },
];
const Asie = [
  {
    'code': 'AF',
    'pays': 'Afghanistan',
    'reponses': ['Kaboul', 'Hérat', 'Mazar-e-Charif', 'Kandahar'],
    'capitale': 'Kaboul',
  },
  {
    'code': 'SA',
    'pays': 'Arabie saoudite',
    'reponses': ['Riyad', 'Djeddah', 'Médine', 'La Mecque'],
    'capitale': 'Riyad',
  },
  {
    'code': 'AM',
    'pays': 'Arménie',
    'reponses': ['Erevan', 'Gyumri', 'Vanadzor', 'Vagharshapat'],
    'capitale': 'Erevan',
  },
  {
    'code': 'AZ',
    'pays': 'Azerbaïdjan',
    'reponses': ['Bakou', 'Gandja', 'Sumqayit', 'Mingachevir'],
    'capitale': 'Bakou',
  },
  {
    'code': 'BH',
    'pays': 'Bahreïn',
    'reponses': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
    'capitale': 'Manama',
  },
  {
    'code': 'BD',
    'pays': 'Bangladesh',
    'reponses': ['Dacca', 'Chittagong', 'Khulna', 'Rajshahi'],
    'capitale': 'Dacca',
  },
  {
    'code': 'BT',
    'pays': 'Bhoutan',
    'reponses': ['Thimphou', 'Phuntsholing', 'Paro', 'Punakha'],
    'capitale': 'Thimphou',
  },
  {
    'code': 'MM',
    'pays': 'Birmanie',
    'reponses': ['Naypyidaw', 'Rangoun', 'Mandalay', 'Moulmein'],
    'capitale': 'Naypyidaw',
  },
  {
    'code': 'BN',
    'pays': 'Brunei',
    'reponses': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'],
    'capitale': 'Bandar Seri Begawan',
  },
  {
    'code': 'KH',
    'pays': 'Cambodge',
    'reponses': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'],
    'capitale': 'Phnom Penh',
  },
  {
    'code': 'CN',
    'pays': 'Chine',
    'reponses': ['Pékin', 'Shanghai', 'Canton', 'Shenzhen'],
    'capitale': 'Pékin',
  },
  {
    'code': 'CY',
    'pays': 'Chypre',
    'reponses': ['Nicosie', 'Limassol', 'Larnaca', 'Paphos'],
    'capitale': 'Nicosie',
  },
  {
    'code': 'KP',
    'pays': 'Corée du Nord',
    'reponses': ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo'],
    'capitale': 'Pyongyang',
  },
  {
    'code': 'KR',
    'pays': 'Corée du Sud',
    'reponses': ['Séoul', 'Busan', 'Incheon', 'Daegu'],
    'capitale': 'Séoul',
  },
  {
    'code': 'AE',
    'pays': 'Émirats arabes unis',
    'reponses': ['Abou Dabi', 'Dubai', 'Charjah', 'Ajman'],
    'capitale': 'Abou Dabi',
  },
  {
    'code': 'GE',
    'pays': 'Géorgie',
    'reponses': ['Tbilissi', 'Koutaïssi', 'Batoumi', 'Soukhoumi'],
    'capitale': 'Tbilissi',
  },
  {
    'code': 'IN',
    'pays': 'Inde',
    'reponses': ['New Delhi', 'Mumbai', 'Bangalore', 'Chennai'],
    'capitale': 'New Delhi',
  },
  {
    'code': 'ID',
    'pays': 'Indonésie',
    'reponses': ['Jakarta', 'Surabaya', 'Bandung', 'Medan'],
    'capitale': 'Jakarta',
  },
  {
    'code': 'IR',
    'pays': 'Iran',
    'reponses': ['Téhéran', 'Mashhad', 'Ispahan', 'Karaj'],
    'capitale': 'Téhéran',
  },
  {
    'code': 'IQ',
    'pays': 'Irak',
    'reponses': ['Bagdad', 'Bassorah', 'Irbil', 'Najaf'],
    'capitale': 'Bagdad',
  },
  {
    'code': 'IL',
    'pays': 'Israël',
    'reponses': ['Jérusalem', 'Tel Aviv', 'Haïfa', 'Rishon LeZion'],
    'capitale': 'Jérusalem',
  },
  {
    'code': 'JP',
    'pays': 'Japon',
    'reponses': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya'],
    'capitale': 'Tokyo',
  },
  {
    'code': 'JO',
    'pays': 'Jordanie',
    'reponses': ['Amman', 'Zarqa', 'Irbid', 'Russeifa'],
    'capitale': 'Amman',
  },
  {
    'code': 'KZ',
    'pays': 'Kazakhstan',
    'reponses': ['Noursoultan', 'Almaty', 'Chymkent', 'Shymkent'],
    'capitale': 'Noursoultan',
  },
  {
    'code': 'KG',
    'pays': 'Kirghizistan',
    'reponses': ['Bichkek', 'Osh', 'Jalal-Abad', 'Karakol'],
    'capitale': 'Bichkek',
  },
  {
    'code': 'KW',
    'pays': 'Koweït',
    'reponses': ['Koweït', 'Al-Ahmadi', 'Hawalli', 'Mubarak Al-Kabeer'],
    'capitale': 'Koweït',
  },
  {
    'code': 'LA',
    'pays': 'Laos',
    'reponses': ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'],
    'capitale': 'Vientiane',
  },
  {
    'code': 'LB',
    'pays': 'Liban',
    'reponses': ['Beyrouth', 'Tripoli', 'Sidon', 'Tyre'],
    'capitale': 'Beyrouth',
  },
  {
    'code': 'MY',
    'pays': 'Malaisie',
    'reponses': ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam'],
    'capitale': 'Kuala Lumpur',
  },
  {
    'code': 'MV',
    'pays': 'Maldives',
    'reponses': ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi'],
    'capitale': 'Malé',
  },
  {
    'code': 'MN',
    'pays': 'Mongolie',
    'reponses': ['Oulan-Bator', 'Darkhan', 'Erdenet', 'Choibalsan'],
    'capitale': 'Oulan-Bator',
  },
  {
    'code': 'NP',
    'pays': 'Népal',
    'reponses': ['Katmandou', 'Pokhara', 'Patan', 'Biratnagar'],
    'capitale': 'Katmandou',
  },
  {
    'code': 'OM',
    'pays': 'Oman',
    'reponses': ['Mascate', 'Salalah', 'Suhar', 'Nizwa'],
    'capitale': 'Mascate',
  },
  {
    'code': 'UZ',
    'pays': 'Ouzbékistan',
    'reponses': ['Tachkent', 'Namangan', 'Andijan', 'Samarkand'],
    'capitale': 'Tachkent',
  },
  {
    'code': 'PK',
    'pays': 'Pakistan',
    'reponses': ['Islamabad', 'Karachi', 'Lahore', 'Faisalabad'],
    'capitale': 'Islamabad',
  },
  {
    'code': 'PS',
    'pays': 'Palestine',
    'reponses': ['Jérusalem-Est', 'Gaza', 'Naplouse', 'Rafah'],
    'capitale': 'Jérusalem-Est',
  },
  {
    'code': 'PH',
    'pays': 'Philippines',
    'reponses': ['Manille', 'Quezon City', 'Davao', 'Cebu City'],
    'capitale': 'Manille',
  },
  {
    'code': 'QA',
    'pays': 'Qatar',
    'reponses': ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah'],
    'capitale': 'Doha',
  },
  {
    'code': 'SG',
    'pays': 'Singapour',
    'reponses': ['Singapour', 'Woodlands', 'Jurong West', 'Tampines'],
    'capitale': 'Singapour',
  },
  {
    'code': 'LK',
    'pays': 'Sri Lanka',
    'reponses': ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Jaffna'],
    'capitale': 'Colombo',
  },
  {
    'code': 'SY',
    'pays': 'Syrie',
    'reponses': ['Damas', 'Alep', 'Homs', 'Hama'],
    'capitale': 'Damas',
  },
  {
    'code': 'TJ',
    'pays': 'Tadjikistan',
    'reponses': ['Douchanbé', 'Khoudjand', 'Qurghonteppa', 'Kulob'],
    'capitale': 'Douchanbé',
  },
  {
    'code': 'TW',
    'pays': 'Taïwan',
    'reponses': ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan'],
    'capitale': 'Taipei',
  },
  {
    'code': 'TH',
    'pays': 'Thaïlande',
    'reponses': ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai'],
    'capitale': 'Bangkok',
  },
  {
    'code': 'TL',
    'pays': 'Timor oriental',
    'reponses': ['Dili', 'Same', 'Baucau', 'Liquiçá'],
    'capitale': 'Dili',
  },
  {
    'code': 'TM',
    'pays': 'Turkménistan',
    'reponses': ['Achgabat', 'Daşoguz', 'Mary', 'Türkmenabat'],
    'capitale': 'Achgabat',
  },
  {
    'code': 'TR',
    'pays': 'Turquie',
    'reponses': ['Ankara', 'Istanbul', 'Izmir', 'Bursa'],
    'capitale': 'Ankara',
  },
  {
    'code': 'VN',
    'pays': 'Viêt Nam',
    'reponses': ['Hanoï', 'Hô Chi Minh-Ville', 'Hải Phòng', 'Cần Thơ'],
    'capitale': 'Hanoï',
  },
  {
    'code': 'YE',
    'pays': 'Yémen',
    'reponses': ['Sanaa', 'Aden', 'Taëz', 'Al Hudaydah'],
    'capitale': 'Sanaa',
  },
];
const Amerique = [
  {
    'code': 'AG',
    'pays': 'Antigua-et-Barbuda',
    'reponses': ['Saint John\'s', 'All Saints', 'Liberta', 'Bolans'],
    'capitale': 'Saint John\'s',
  },
  {
    'code': 'AR',
    'pays': 'Argentine',
    'reponses': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'],
    'capitale': 'Buenos Aires',
  },
  {
    'code': 'BS',
    'pays': 'Bahamas',
    'reponses': ['Nassau', 'Freeport', 'Lucaya', 'West End'],
    'capitale': 'Nassau',
  },
  {
    'code': 'BB',
    'pays': 'Barbade',
    'reponses': ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba'],
    'capitale': 'Bridgetown',
  },
  {
    'code': 'BZ',
    'pays': 'Belize',
    'reponses': ['Belmopan', 'Belize City', 'San Ignacio', 'Orange Walk'],
    'capitale': 'Belmopan',
  },
  {
    'code': 'BO',
    'pays': 'Bolivie',
    'reponses': ['La Paz', 'Sucre', 'Cochabamba', 'Oruro'],
    'capitale': 'La Paz',
  },
  {
    'code': 'BR',
    'pays': 'Brésil',
    'reponses': ['Brasília', 'São Paulo', 'Rio de Janeiro', 'Salvador'],
    'capitale': 'Brasília',
  },
  {
    'code': 'CA',
    'pays': 'Canada',
    'reponses': ['Ottawa', 'Toronto', 'Montréal', 'Vancouver'],
    'capitale': 'Ottawa',
  },
  {
    'code': 'CL',
    'pays': 'Chili',
    'reponses': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena'],
    'capitale': 'Santiago',
  },
  {
    'code': 'CO',
    'pays': 'Colombie',
    'reponses': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'],
    'capitale': 'Bogotá',
  },
  {
    'code': 'CR',
    'pays': 'Costa Rica',
    'reponses': ['San José', 'Limon', 'San Francisco', 'Alajuela'],
    'capitale': 'San José',
  },
  {
    'code': 'CU',
    'pays': 'Cuba',
    'reponses': ['La Havane', 'Santiago de Cuba', 'Camagüey', 'Holguín'],
    'capitale': 'La Havane',
  },
  {
    'code': 'DO',
    'pays': 'République dominicaine',
    'reponses': [
      'Saint-Domingue',
      'Santiago de los Caballeros',
      'Santo Domingo Este',
      'San Pedro de Macorís'
    ],
    'capitale': 'Saint-Domingue',
  },
  {
    'code': 'DM',
    'pays': 'Dominique',
    'reponses': ['Roseau', 'Portsmouth', 'Marigot', 'Berekua'],
    'capitale': 'Roseau',
  },
  {
    'code': 'EC',
    'pays': 'Équateur',
    'reponses': ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo'],
    'capitale': 'Quito',
  },
  {
    'code': 'US',
    'pays': 'États-Unis',
    'reponses': ['Washington', 'New York', 'Los Angeles', 'Chicago'],
    'capitale': 'Washington',
  },
  {
    'code': 'GD',
    'pays': 'Grenade',
    'reponses': ['Saint George\'s', 'Gouyave', 'Grenville', 'Victoria'],
    'capitale': 'Saint George\'s',
  },
  {
    'code': 'GT',
    'pays': 'Guatemala',
    'reponses': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'],
    'capitale': 'Guatemala City',
  },
  {
    'code': 'GY',
    'pays': 'Guyana',
    'reponses': ['Georgetown', 'Linden', 'New Amsterdam', 'Bartica'],
    'capitale': 'Georgetown',
  },
  {
    'code': 'HT',
    'pays': 'Haïti',
    'reponses': ['Port-au-Prince', 'Cap-Haïtien', 'Carrefour', 'Delmas'],
    'capitale': 'Port-au-Prince',
  },
  {
    'code': 'HN',
    'pays': 'Honduras',
    'reponses': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'],
    'capitale': 'Tegucigalpa',
  },
  {
    'code': 'JM',
    'pays': 'Jamaïque',
    'reponses': ['Kingston', 'New Kingston', 'Spanish Town', 'Montego Bay'],
    'capitale': 'Kingston',
  },
  {
    'code': 'MX',
    'pays': 'Mexique',
    'reponses': ['Mexico', 'Guadalajara', 'Monterrey', 'Puebla'],
    'capitale': 'Mexico',
  },
  {
    'code': 'NI',
    'pays': 'Nicaragua',
    'reponses': ['Managua', 'León', 'Masaya', 'Matagalpa'],
    'capitale': 'Managua',
  },
  {
    'code': 'PA',
    'pays': 'Panama',
    'reponses': ['Panama City', 'San Miguelito', 'Tocumen', 'David'],
    'capitale': 'Panama City',
  },
  {
    'code': 'PY',
    'pays': 'Paraguay',
    'reponses': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Lambaré'],
    'capitale': 'Asunción',
  },
  {
    'code': 'PE',
    'pays': 'Pérou',
    'reponses': ['Lima', 'Arequipa', 'Callao', 'Trujillo'],
    'capitale': 'Lima',
  },
  {
    'code': 'KN',
    'pays': 'Saint-Christophe-et-Niévès',
    'reponses': [
      'Basseterre',
      'Charlestown',
      'Dieppe Bay Town',
      'Half Way Tree'
    ],
    'capitale': 'Basseterre',
  },
  {
    'code': 'LC',
    'pays': 'Sainte-Lucie',
    'reponses': ['Castries', 'Vieux Fort', 'Micoud', 'Soufrière'],
    'capitale': 'Castries',
  },
  {
    'code': 'VC',
    'pays': 'Saint-Vincent-et-les-Grenadines',
    'reponses': ['Kingstown', 'Kingstown Park', 'Arnos Vale', 'Port Elizabeth'],
    'capitale': 'Kingstown',
  },
  {
    'code': 'SV',
    'pays': 'Salvador',
    'reponses': ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel'],
    'capitale': 'San Salvador',
  },
  {
    'code': 'SR',
    'pays': 'Suriname',
    'reponses': ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo'],
    'capitale': 'Paramaribo',
  },
  {
    'code': 'TT',
    'pays': 'Trinité-et-Tobago',
    'reponses': ['Port of Spain', 'Chaguanas', 'San Fernando', 'Arima'],
    'capitale': 'Port of Spain',
  },
  {
    'code': 'UY',
    'pays': 'Uruguay',
    'reponses': ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú'],
    'capitale': 'Montevideo',
  },
  {
    'code': 'VE',
    'pays': 'Venezuela',
    'reponses': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto'],
    'capitale': 'Caracas',
  },
];
const Europe = [
  {
    'code': 'AL',
    'pays': 'Albanie',
    'reponses': ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'],
    'capitale': 'Tirana',
  },
  {
    'code': 'DE',
    'pays': 'Allemagne',
    'reponses': ['Berlin', 'Hambourg', 'Munich', 'Cologne'],
    'capitale': 'Berlin',
  },
  {
    'code': 'AD',
    'pays': 'Andorre',
    'reponses': [
      'Andorre-la-Vieille',
      'Escaldes-Engordany',
      'Encamp',
      'Sant Julià de Lòria'
    ],
    'capitale': 'Andorre-la-Vieille',
  },
  {
    'code': 'AT',
    'pays': 'Autriche',
    'reponses': ['Vienne', 'Graz', 'Linz', 'Salzbourg'],
    'capitale': 'Vienne',
  },
  {
    'code': 'BE',
    'pays': 'Belgique',
    'reponses': ['Bruxelles', 'Anvers', 'Gand', 'Charleroi'],
    'capitale': 'Bruxelles',
  },
  {
    'code': 'BY',
    'pays': 'Biélorussie',
    'reponses': ['Minsk', 'Hrodna', 'Brest', 'Moguilev'],
    'capitale': 'Minsk',
  },
  {
    'code': 'BA',
    'pays': 'Bosnie-Herzégovine',
    'reponses': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Mostar'],
    'capitale': 'Sarajevo',
  },
  {
    'code': 'BG',
    'pays': 'Bulgarie',
    'reponses': ['Sofia', 'Plovdiv', 'Varna', 'Bourgas'],
    'capitale': 'Sofia',
  },
  {
    'code': 'CY',
    'pays': 'Chypre',
    'reponses': ['Nicosie', 'Limassol', 'Larnaca', 'Paphos'],
    'capitale': 'Nicosie',
  },
  {
    'code': 'HR',
    'pays': 'Croatie',
    'reponses': ['Zagreb', 'Split', 'Rijeka', 'Osijek'],
    'capitale': 'Zagreb',
  },
  {
    'code': 'DK',
    'pays': 'Danemark',
    'reponses': ['Copenhague', 'Aarhus', 'Odense', 'Aalborg'],
    'capitale': 'Copenhague',
  },
  {
    'code': 'ES',
    'pays': 'Espagne',
    'reponses': ['Madrid', 'Barcelone', 'Valence', 'Séville'],
    'capitale': 'Madrid',
  },
  {
    'code': 'EE',
    'pays': 'Estonie',
    'reponses': ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
    'capitale': 'Tallinn',
  },
  {
    'code': 'FI',
    'pays': 'Finlande',
    'reponses': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'],
    'capitale': 'Helsinki',
  },
  {
    'code': 'FR',
    'pays': 'France',
    'reponses': ['Paris', 'Marseille', 'Lyon', 'Toulouse'],
    'capitale': 'Paris',
  },
  {
    'code': 'GR',
    'pays': 'Grèce',
    'reponses': ['Athènes', 'Thessalonique', 'Patras', 'Héraklion'],
    'capitale': 'Athènes',
  },
  {
    'code': 'HU',
    'pays': 'Hongrie',
    'reponses': ['Budapest', 'Debrecen', 'Miskolc', 'Szeged'],
    'capitale': 'Budapest',
  },
  {
    'code': 'IE',
    'pays': 'Irlande',
    'reponses': ['Dublin', 'Cork', 'Galway', 'Limerick'],
    'capitale': 'Dublin',
  },
  {
    'code': 'IS',
    'pays': 'Islande',
    'reponses': ['Reykjavik', 'Kopavogur', 'Hafnarfjordur', 'Akureyri'],
    'capitale': 'Reykjavik',
  },
  {
    'code': 'IT',
    'pays': 'Italie',
    'reponses': ['Rome', 'Milan', 'Naples', 'Turin'],
    'capitale': 'Rome',
  },
  {
    'code': 'KZ',
    'pays': 'Kazakhstan',
    'reponses': ['Noursoultan', 'Almaty', 'Chymkent', 'Shymkent'],
    'capitale': 'Noursoultan',
  },
  {
    'code': 'XK',
    'pays': 'Kosovo',
    'reponses': ['Pristina', 'Mitrovica', 'Prizren', 'Peja'],
    'capitale': 'Pristina',
  },
  {
    'code': 'LV',
    'pays': 'Lettonie',
    'reponses': ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava'],
    'capitale': 'Riga',
  },
  {
    'code': 'LI',
    'pays': 'Liechtenstein',
    'reponses': ['Vaduz', 'Schaan', 'Triesen', 'Balzers'],
    'capitale': 'Vaduz',
  },
  {
    'code': 'LT',
    'pays': 'Lituanie',
    'reponses': ['Vilnius', 'Kaunas', 'Klaipeda', 'Šiauliai'],
    'capitale': 'Vilnius',
  },
  {
    'code': 'LU',
    'pays': 'Luxembourg',
    'reponses': ['Luxembourg', 'Esch-sur-Alzette', 'Dudelange', 'Differdange'],
    'capitale': 'Luxembourg',
  },
  {
    'code': 'MK',
    'pays': 'Macédoine du Nord',
    'reponses': ['Skopje', 'Bitola', 'Kumanovo', 'Prilep'],
    'capitale': 'Skopje',
  },
  {
    'code': 'MT',
    'pays': 'Malte',
    'reponses': ['La Valette', 'Birkirkara', 'Mosta', 'Qormi'],
    'capitale': 'La Valette',
  },
  {
    'code': 'MD',
    'pays': 'Moldavie',
    'reponses': ['Chișinău', 'Tiraspol', 'Bălți', 'Bender'],
    'capitale': 'Chișinău',
  },
  {
    'code': 'MC',
    'pays': 'Monaco',
    'reponses': ['Monaco', 'Monte-Carlo', 'La Condamine', 'Fontvieille'],
    'capitale': 'Monaco',
  },
  {
    'code': 'ME',
    'pays': 'Monténégro',
    'reponses': ['Podgorica', 'Nikšić', 'Herceg Novi', 'Bar'],
    'capitale': 'Podgorica',
  },
  {
    'code': 'NO',
    'pays': 'Norvège',
    'reponses': ['Oslo', 'Bergen', 'Stavanger', 'Trondheim'],
    'capitale': 'Oslo',
  },
  {
    'code': 'NL',
    'pays': 'Pays-Bas',
    'reponses': ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht'],
    'capitale': 'Amsterdam',
  },
  {
    'code': 'PL',
    'pays': 'Pologne',
    'reponses': ['Varsovie', 'Cracovie', 'Łódź', 'Wrocław'],
    'capitale': 'Varsovie',
  },
  {
    'code': 'PT',
    'pays': 'Portugal',
    'reponses': ['Lisbonne', 'Porto', 'Vila Nova de Gaia', 'Amadora'],
    'capitale': 'Lisbonne',
  },
  {
    'code': 'CZ',
    'pays': 'République tchèque',
    'reponses': ['Prague', 'Brno', 'Ostrava', 'Plzeň'],
    'capitale': 'Prague',
  },
  {
    'code': 'RO',
    'pays': 'Roumanie',
    'reponses': ['Bucarest', 'Cluj-Napoca', 'Timișoara', 'Iași'],
    'capitale': 'Bucarest',
  },
  {
    'code': 'GB',
    'pays': 'Royaume-Uni',
    'reponses': ['Londres', 'Birmingham', 'Manchester', 'Glasgow'],
    'capitale': 'Londres',
  },
  {
    'code': 'RU',
    'pays': 'Russie',
    'reponses': [
      'Moscou',
      'Saint-Pétersbourg',
      'Novossibirsk',
      'Iekaterinbourg'
    ],
    'capitale': 'Moscou',
  },
  {
    'code': 'SM',
    'pays': 'Saint-Marin',
    'reponses': ['Saint-Marin', 'Serravalle', 'Domagnano', 'Borgo Maggiore'],
    'capitale': 'Saint-Marin',
  },
  {
    'code': 'RS',
    'pays': 'Serbie',
    'reponses': ['Belgrade', 'Niš', 'Novi Sad', 'Kragujevac'],
    'capitale': 'Belgrade',
  },
  {
    'code': 'SK',
    'pays': 'Slovaquie',
    'reponses': ['Bratislava', 'Košice', 'Prešov', 'Žilina'],
    'capitale': 'Bratislava',
  },
  {
    'code': 'SI',
    'pays': 'Slovénie',
    'reponses': ['Ljubljana', 'Maribor', 'Celje', 'Kranj'],
    'capitale': 'Ljubljana',
  },
  {
    'code': 'SE',
    'pays': 'Suède',
    'reponses': ['Stockholm', 'Göteborg', 'Malmö', 'Uppsala'],
    'capitale': 'Stockholm',
  },
  {
    'code': 'CH',
    'pays': 'Suisse',
    'reponses': ['Berne', 'Zurich', 'Genève', 'Bâle'],
    'capitale': 'Berne',
  },
  {
    'code': 'UA',
    'pays': 'Ukraine',
    'reponses': ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro'],
    'capitale': 'Kiev',
  },
  {
    'code': 'VA',
    'pays': 'Vatican',
    'reponses': ['Cité du Vatican'],
    'capitale': 'Cité du Vatican',
  },
];
const Oceanie = [
  {
    'code': 'AU',
    'pays': 'Australie',
    'reponses': ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    'capitale': 'Canberra',
  },
  {
    'code': 'FJ',
    'pays': 'Fidji',
    'reponses': ['Suva', 'Lautoka', 'Nadi', 'Labasa'],
    'capitale': 'Suva',
  },
  {
    'code': 'MH',
    'pays': 'Îles Marshall',
    'reponses': ['Majuro', 'Ebeye', 'Jabor', 'Laura'],
    'capitale': 'Majuro',
  },
  {
    'code': 'KI',
    'pays': 'Kiribati',
    'reponses': ['Tarawa', 'Betio', 'Bikenibeu', 'Teaoraereke'],
    'capitale': 'Tarawa',
  },
  {
    'code': 'FM',
    'pays': 'Micronésie',
    'reponses': ['Palikir', 'Weno', 'Colonia', 'Tofol'],
    'capitale': 'Palikir',
  },
  {
    'code': 'NR',
    'pays': 'Nauru',
    'reponses': ['Yaren', 'Denigomodu', 'Meneng', 'Buada'],
    'capitale': 'Yaren',
  },
  {
    'code': 'NZ',
    'pays': 'Nouvelle-Zélande',
    'reponses': ['Wellington', 'Auckland', 'Christchurch', 'Hamilton'],
    'capitale': 'Wellington',
  },
  {
    'code': 'PW',
    'pays': 'Palaos',
    'reponses': ['Ngerulmud', 'Koror', 'Airai', 'Melekeok'],
    'capitale': 'Ngerulmud',
  },
  {
    'code': 'PG',
    'pays': 'Papouasie-Nouvelle-Guinée',
    'reponses': ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang'],
    'capitale': 'Port Moresby',
  },
  {
    'code': 'SB',
    'pays': 'Salomon',
    'reponses': ['Honiara', 'Gizo', 'Auki', 'Kirakira'],
    'capitale': 'Honiara',
  },
  {
    'code': 'WS',
    'pays': 'Samoa',
    'reponses': ['Apia', 'Asau', 'Mulifanua', 'Faleula'],
    'capitale': 'Apia',
  },
  {
    'code': 'TO',
    'pays': 'Tonga',
    'reponses': ['Nukuʻalofa', 'Neiafu', 'Vaini', 'Haveluloto'],
    'capitale': 'Nukuʻalofa',
  },
  {
    'code': 'TV',
    'pays': 'Tuvalu',
    'reponses': ['Funafuti', 'Fongafale', 'Vaiaku', 'Alapi'],
    'capitale': 'Funafuti',
  },
  {
    'code': 'VU',
    'pays': 'Vanuatu',
    'reponses': ['Port-Vila', 'Luganville', 'Norsup', 'Sola'],
    'capitale': 'Port-Vila',
  },
];
